export const rankingMock = [
  {
    id: "1",
    rank: { name: "Private", image: "/ranks/private.png" },
    avatarUrl: "/avatar.png",
    username: "John Doe",
    ratio: "0/0",
    score: 0,
  },
  {
    id: "2",
    rank: { name: "Private", image: "/ranks/private.png" },
    avatarUrl: "/avatar.png",
    username: "Jack Richer",
    ratio: "0/1",
    score: 0.5,
  },
  {
    id: "3",
    rank: { name: "Sergeant Major", image: "/ranks/sergeant-major.png" },
    avatarUrl: "/avatar.png",
    username: "Bruce Wayne",
    ratio: "1/0",
    score: 2,
  },
  {
    id: "4",
    rank: { name: "Warrant Officer", image: "/ranks/warrant-officer.png" },
    avatarUrl: "/avatar.png",
    username: "Peter Parker",
    ratio: "1/1",
    score: 2.5,
  },
  {
    id: "5",
    rank: { name: "Warrant Officer", image: "/ranks/warrant-officer.png" },
    avatarUrl: "/avatar.png",
    username: "Clark Kent",
    ratio: "1/2",
    score: 3,
  },
  {
    id: "6",
    rank: { name: "First Lieutenant", image: "/ranks/first-lieutenant.png" },
    avatarUrl: "/avatar.png",
    username: "Tony Stark",
    ratio: "2/2",
    score: 5,
  },
  {
    id: "7",
    rank: { name: "Captain", image: "/ranks/captain.png" },
    avatarUrl: "/avatar.png",
    username: "Rick Sanchez",
    ratio: "2/3",
    score: 5.5,
  },
  {
    id: "8",
    rank: { name: "Major", image: "/ranks/major.png" },
    avatarUrl: "/avatar.png",
    username: "Kyle Broflovski",
    ratio: "3/3",
    score: 7.5,
  },
  {
    id: "9",
    rank: { name: "Major", image: "/ranks/major.png" },
    avatarUrl: "/avatar.png",
    username: "Eric Cartman",
    ratio: "3/1",
    score: 6.5,
  },
  {
    id: "10",
    rank: { name: "Major", image: "/ranks/major.png" },
    avatarUrl: "/avatar.png",
    username: "Stan Marsh",
    ratio: "3/2",
    score: 7,
  },
  {
    id: "11",
    rank: { name: "General of the Army", image: "/ranks/general-army.png" },
    avatarUrl: "/avatar.png",
    username: "Martha Stewart",
    ratio: "4/4",
    score: 10,
  },
  {
    id: "12",
    rank: { name: "General of the Army", image: "/ranks/general-army.png" },
    avatarUrl: "/avatar.png",
    username: "Kenny McCormick",
    ratio: "4/3",
    score: 9.5,
  },
  {
    id: "13",
    rank: { name: "General", image: "/ranks/general.png" },
    avatarUrl: "/avatar.png",
    username: "Cartman",
    ratio: "4/2",
    score: 9,
  },
];
